# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ApproxAvgPostIntensity <- function(genmix, lamdas, LL, burnin, xlims, ylims, approxcomp) {
    .Call('sppmix_ApproxAvgPostIntensity', PACKAGE = 'sppmix', genmix, lamdas, LL, burnin, xlims, ylims, approxcomp)
}

ApproxCompMass_sppmix <- function(xlims, ylims, mu, sigma) {
    .Call('sppmix_ApproxCompMass_sppmix', PACKAGE = 'sppmix', xlims, ylims, mu, sigma)
}

ApproxMHRatiosig_sppmix <- function(xlims, ylims, mu, cursigma, propsigma, num) {
    .Call('sppmix_ApproxMHRatiosig_sppmix', PACKAGE = 'sppmix', xlims, ylims, mu, cursigma, propsigma, num)
}

ApproxBayesianModelAvgIntensity_sppmix <- function(genBDmix, lamdas, numcomp, distr_numcomp, mincomp, maxcomp, LL, xlims, ylims, approxcomp) {
    .Call('sppmix_ApproxBayesianModelAvgIntensity_sppmix', PACKAGE = 'sppmix', genBDmix, lamdas, numcomp, distr_numcomp, mincomp, maxcomp, LL, xlims, ylims, approxcomp)
}

BDMCMC2d_sppmix <- function(maxnumcomp, points, xlims, ylims, L, truncate, lamda, lamdab, hyper) {
    .Call('sppmix_BDMCMC2d_sppmix', PACKAGE = 'sppmix', maxnumcomp, points, xlims, ylims, L, truncate, lamda, lamdab, hyper)
}

DAMCMC2d_sppmix <- function(points, xlims, ylims, m, L, truncate, hyperparams, useKmeans) {
    .Call('sppmix_DAMCMC2d_sppmix', PACKAGE = 'sppmix', points, xlims, ylims, m, L, truncate, hyperparams, useKmeans)
}

DAMCMC2dRMCP_sppmix <- function(points, xlims, ylims, m, L, truncate, d, mu0, Sigma0, df0, sig0, useKmeans, startmus) {
    .Call('sppmix_DAMCMC2dRMCP_sppmix', PACKAGE = 'sppmix', points, xlims, ylims, m, L, truncate, d, mu0, Sigma0, df0, sig0, useKmeans, startmus)
}

TriangleArea <- function(a, b, c) {
    .Call('sppmix_TriangleArea', PACKAGE = 'sppmix', a, b, c)
}

CheckTriangleCLockwise <- function(a, b, c) {
    .Call('sppmix_CheckTriangleCLockwise', PACKAGE = 'sppmix', a, b, c)
}

CheckInPoly <- function(poly, xy) {
    .Call('sppmix_CheckInPoly', PACKAGE = 'sppmix', poly, xy)
}

MatrixNorm <- function(M, p) {
    .Call('sppmix_MatrixNorm', PACKAGE = 'sppmix', M, p)
}

MatTrace <- function(M) {
    .Call('sppmix_MatTrace', PACKAGE = 'sppmix', M)
}

Quad_sppmix <- function(v, m) {
    .Call('sppmix_Quad_sppmix', PACKAGE = 'sppmix', v, m)
}

VecNorm2 <- function(v) {
    .Call('sppmix_VecNorm2', PACKAGE = 'sppmix', v)
}

VecLen2 <- function(v) {
    .Call('sppmix_VecLen2', PACKAGE = 'sppmix', v)
}

SQ_sppmix <- function(x) {
    .Call('sppmix_SQ_sppmix', PACKAGE = 'sppmix', x)
}

Factorial_sppmix <- function(x) {
    .Call('sppmix_Factorial_sppmix', PACKAGE = 'sppmix', x)
}

invmat2d_sppmix <- function(A) {
    .Call('sppmix_invmat2d_sppmix', PACKAGE = 'sppmix', A)
}

densNormMixatx_sppmix <- function(atx, mix, approxcomp) {
    .Call('sppmix_densNormMixatx_sppmix', PACKAGE = 'sppmix', atx, mix, approxcomp)
}

densNormMix_atxy_sppmix <- function(atxy, mix, approxcomp) {
    .Call('sppmix_densNormMix_atxy_sppmix', PACKAGE = 'sppmix', atxy, mix, approxcomp)
}

dNormMix_sppmix <- function(mix, x, y, approxcomp) {
    .Call('sppmix_dNormMix_sppmix', PACKAGE = 'sppmix', mix, x, y, approxcomp)
}

Permute_vec_sppmix <- function(oldvec, perm) {
    .Call('sppmix_Permute_vec_sppmix', PACKAGE = 'sppmix', oldvec, perm)
}

Permute_mat_sppmix <- function(oldmat, perm) {
    .Call('sppmix_Permute_mat_sppmix', PACKAGE = 'sppmix', oldmat, perm)
}

GetAllPermutations_sppmix <- function(m) {
    .Call('sppmix_GetAllPermutations_sppmix', PACKAGE = 'sppmix', m)
}

GetAPermutation_sppmix <- function(m, which) {
    .Call('sppmix_GetAPermutation_sppmix', PACKAGE = 'sppmix', m, which)
}

GetGrid_sppmix <- function(len, xlims, ylims) {
    .Call('sppmix_GetGrid_sppmix', PACKAGE = 'sppmix', len, xlims, ylims)
}

EqVec_sppmix <- function(v1, v2, tol) {
    .Call('sppmix_EqVec_sppmix', PACKAGE = 'sppmix', v1, v2, tol)
}

logGammaFunc_sppmix <- function(x) {
    .Call('sppmix_logGammaFunc_sppmix', PACKAGE = 'sppmix', x)
}

GammaFunc_sppmix <- function(x) {
    .Call('sppmix_GammaFunc_sppmix', PACKAGE = 'sppmix', x)
}

dDirichlet_sppmix <- function(ps, ds) {
    .Call('sppmix_dDirichlet_sppmix', PACKAGE = 'sppmix', ps, ds)
}

SumVec_sppmix <- function(v, start, end) {
    .Call('sppmix_SumVec_sppmix', PACKAGE = 'sppmix', v, start, end)
}

SubstituteVec_sppmix <- function(v, subv, start) {
    .Call('sppmix_SubstituteVec_sppmix', PACKAGE = 'sppmix', v, subv, start)
}

SubVec_sppmix <- function(v, start, end) {
    .Call('sppmix_SubVec_sppmix', PACKAGE = 'sppmix', v, start, end)
}

GetMixtureMaxz_sppmix <- function(genmix, len, xlims, ylims, approxcomp) {
    .Call('sppmix_GetMixtureMaxz_sppmix', PACKAGE = 'sppmix', genmix, len, xlims, ylims, approxcomp)
}

MakeMixtureList_sppmix <- function(gens_list, burnin) {
    .Call('sppmix_MakeMixtureList_sppmix', PACKAGE = 'sppmix', gens_list, burnin)
}

CheckInWindow_sppmix <- function(points, xlims, ylims, truncate, show) {
    .Call('sppmix_CheckInWindow_sppmix', PACKAGE = 'sppmix', points, xlims, ylims, truncate, show)
}

GetMax_sppmix <- function(v) {
    .Call('sppmix_GetMax_sppmix', PACKAGE = 'sppmix', v)
}

dNormal1d_sppmix <- function(atx, mu, sigsq) {
    .Call('sppmix_dNormal1d_sppmix', PACKAGE = 'sppmix', atx, mu, sigsq)
}

dNormal_sppmix <- function(atx, mu, sig) {
    .Call('sppmix_dNormal_sppmix', PACKAGE = 'sppmix', atx, mu, sig)
}

MultGamma <- function(p, n) {
    .Call('sppmix_MultGamma', PACKAGE = 'sppmix', p, n)
}

dInvWishart_sppmix <- function(W, df, alpha) {
    .Call('sppmix_dInvWishart_sppmix', PACKAGE = 'sppmix', W, df, alpha)
}

MIPPCondLoc_sppmix <- function(points, marks, xlims, ylims, L, truncate, hyperparams, uniquemarks, discrete_mark, r) {
    .Call('sppmix_MIPPCondLoc_sppmix', PACKAGE = 'sppmix', points, marks, xlims, ylims, L, truncate, hyperparams, uniquemarks, discrete_mark, r)
}

GetProbFieldsCondLoc_sppmix <- function(points, marks, xlims, ylims, LL, meangamma, uniquemarks, truncate, r) {
    .Call('sppmix_GetProbFieldsCondLoc_sppmix', PACKAGE = 'sppmix', points, marks, xlims, ylims, LL, meangamma, uniquemarks, truncate, r)
}

GenMarksProbCondLoc_sppmix <- function(points, L, xlims, ylims, meangamma, uniquemarks, truncate, r) {
    .Call('sppmix_GenMarksProbCondLoc_sppmix', PACKAGE = 'sppmix', points, L, xlims, ylims, meangamma, uniquemarks, truncate, r)
}

GetProbCondLoc_sppmix <- function(points, origmarks, xlims, ylims, meangamma, uniquemarks, truncate, r) {
    .Call('sppmix_GetProbCondLoc_sppmix', PACKAGE = 'sppmix', points, origmarks, xlims, ylims, meangamma, uniquemarks, truncate, r)
}

GetPriorVals_sppmix <- function(pp, allgens, priortype, d, mu0, Sigma0, df0, sig0) {
    .Call('sppmix_GetPriorVals_sppmix', PACKAGE = 'sppmix', pp, allgens, priortype, d, mu0, Sigma0, df0, sig0)
}

GetStats_sppmix <- function(gens, alpha) {
    .Call('sppmix_GetStats_sppmix', PACKAGE = 'sppmix', gens, alpha)
}

GetAllRealiz_ps_sppmix <- function(allgens) {
    .Call('sppmix_GetAllRealiz_ps_sppmix', PACKAGE = 'sppmix', allgens)
}

GetAllRealiz_mus_sppmix <- function(allgens) {
    .Call('sppmix_GetAllRealiz_mus_sppmix', PACKAGE = 'sppmix', allgens)
}

GetAllRealiz_sigmas_sppmix <- function(allgens) {
    .Call('sppmix_GetAllRealiz_sigmas_sppmix', PACKAGE = 'sppmix', allgens)
}

GetRealiz_ps_sppmix <- function(allgens, realiz) {
    .Call('sppmix_GetRealiz_ps_sppmix', PACKAGE = 'sppmix', allgens, realiz)
}

GetRealiz_mus_sppmix <- function(allgens, realiz) {
    .Call('sppmix_GetRealiz_mus_sppmix', PACKAGE = 'sppmix', allgens, realiz)
}

GetRealiz_sigmas_sppmix <- function(allgens, realiz) {
    .Call('sppmix_GetRealiz_sigmas_sppmix', PACKAGE = 'sppmix', allgens, realiz)
}

PostGenGetBestPerm_sppmix <- function(allgens) {
    .Call('sppmix_PostGenGetBestPerm_sppmix', PACKAGE = 'sppmix', allgens)
}

GetAllMeans_sppmix <- function(allgens, burnin) {
    .Call('sppmix_GetAllMeans_sppmix', PACKAGE = 'sppmix', allgens, burnin)
}

GetCompDistr_sppmix <- function(numcomp, maxnumcomp) {
    .Call('sppmix_GetCompDistr_sppmix', PACKAGE = 'sppmix', numcomp, maxnumcomp)
}

GetBDCompRealiz_sppmix <- function(genBDmix, genlamdas, numcomp, comp) {
    .Call('sppmix_GetBDCompRealiz_sppmix', PACKAGE = 'sppmix', genBDmix, genlamdas, numcomp, comp)
}

GetAvgLabelsDiscrete2Multinomial_sppmix <- function(genzs, m) {
    .Call('sppmix_GetAvgLabelsDiscrete2Multinomial_sppmix', PACKAGE = 'sppmix', genzs, m)
}

Check4LabelSwitching_sppmix <- function(chain, lag) {
    .Call('sppmix_Check4LabelSwitching_sppmix', PACKAGE = 'sppmix', chain, lag)
}

PostGenGetBestPermIdenConstraint_sppmix <- function(allgens) {
    .Call('sppmix_PostGenGetBestPermIdenConstraint_sppmix', PACKAGE = 'sppmix', allgens)
}

PermuteZs_sppmix <- function(allgens_zs, bestperm) {
    .Call('sppmix_PermuteZs_sppmix', PACKAGE = 'sppmix', allgens_zs, bestperm)
}

FisherInfoMat_sppmix <- function(data, map_ps, map_mus, map_sigmas, map_zs) {
    .Call('sppmix_FisherInfoMat_sppmix', PACKAGE = 'sppmix', data, map_ps, map_mus, map_sigmas, map_zs)
}

GetDensityValues_sppmix <- function(data, fit, xlims, ylims) {
    .Call('sppmix_GetDensityValues_sppmix', PACKAGE = 'sppmix', data, fit, xlims, ylims)
}

ComputeBayesFactor_sppmix <- function(densvals1, densvals2) {
    .Call('sppmix_ComputeBayesFactor_sppmix', PACKAGE = 'sppmix', densvals1, densvals2)
}

ApproxBivNormProb_sppmix <- function(xlims, ylims, mu, sigma, type) {
    .Call('sppmix_ApproxBivNormProb_sppmix', PACKAGE = 'sppmix', xlims, ylims, mu, sigma, type)
}

rnorm2_sppmix <- function(n, mu, sigma) {
    .Call('sppmix_rnorm2_sppmix', PACKAGE = 'sppmix', n, mu, sigma)
}

rWishart_sppmix <- function(df, A) {
    .Call('sppmix_rWishart_sppmix', PACKAGE = 'sppmix', df, A)
}

rDiscrete_sppmix <- function(start, probs) {
    .Call('sppmix_rDiscrete_sppmix', PACKAGE = 'sppmix', start, probs)
}

rBinom_sppmix <- function(n, p) {
    .Call('sppmix_rBinom_sppmix', PACKAGE = 'sppmix', n, p)
}

rExp_sppmix <- function(a) {
    .Call('sppmix_rExp_sppmix', PACKAGE = 'sppmix', a)
}

rDirichlet_sppmix <- function(d) {
    .Call('sppmix_rDirichlet_sppmix', PACKAGE = 'sppmix', d)
}

rMultinomial_sppmix <- function(n, ps) {
    .Call('sppmix_rMultinomial_sppmix', PACKAGE = 'sppmix', n, ps)
}

rNormMix_sppmix <- function(lamda, mix) {
    .Call('sppmix_rNormMix_sppmix', PACKAGE = 'sppmix', lamda, mix)
}

rPerm_sppmix <- function(n) {
    .Call('sppmix_rPerm_sppmix', PACKAGE = 'sppmix', n)
}

rmvnorm_sppmix <- function(mu, sigma) {
    .Call('sppmix_rmvnorm_sppmix', PACKAGE = 'sppmix', mu, sigma)
}

